spring:
  mail:
    host: smtp.qq.com
    port: 465
    username: 524259885@qq.com
    password: David19930305
    default-encoding: utf-8
    protocol: smtp
    properties:
      to: hehandadad.wang@happyelements.com
      mail:
        smtp:
          auth: true #授权
          starttls:
            enable: true
            required: true
